src/objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Monthly_Spending_RMB__c</fullName>
        <defaultValue>0</defaultValue>
        <label>本月消费金额(￥)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Spending_RMB__c</fullName>
        <defaultValue>0</defaultValue>
        <label>总消费金额(￥)</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>微信昵称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FI_STATS__c.object
<CustomObject>
    <fields>
        <fullName>Profit_RMB__c</fullName>
        <label>利润(￥)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Revenue_RMB__c</fullName>
        <label>销售额(￥)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>FI_STATS</label>
    <nameField>
        <displayFormat>FI-{000000}</displayFormat>
        <label>FI_STATS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FI_STATS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <label>买家</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>订单</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Cost_RMB__c</fullName>
        <label>订单成本总额(￥)</label>
        <summarizedField>OrderLineItem__c.Cost_RMB__c</summarizedField>
        <summaryForeignKey>OrderLineItem__c.Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Price_RMB__c</fullName>
        <label>订单价格总额(￥)</label>
        <summarizedField>OrderLineItem__c.Price_RMB__c</summarizedField>
        <summaryForeignKey>OrderLineItem__c.Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>订单编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Cost_RMB__c</fullName>
        <label>成本(￥)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>订单</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>订单项</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Packet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>包裹</label>
        <referenceTo>Packet__c</referenceTo>
        <relationshipLabel>订单项</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_RMB__c</fullName>
        <label>价格(￥)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>产品</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderLineItems</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OrderLineItem</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>订单项编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Packet__c.object
<CustomObject>
    <fields>
        <fullName>Cost_RMB__c</fullName>
        <label>运费(￥)</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Packet</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>包裹编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Current_Profit_RMB__c</fullName>
        <defaultValue>0</defaultValue>
        <label>当期利润(￥)</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>当期销量</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Revenue_RMB__c</fullName>
        <defaultValue>0</defaultValue>
        <label>当期销售额(￥)</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_RMB__c</fullName>
        <label>价格(￥)</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Profit_RMB__c</fullName>
        <defaultValue>0</defaultValue>
        <label>总利润(￥)</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>总销量</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Revenue_RMB__c</fullName>
        <defaultValue>0</defaultValue>
        <label>总销售额(￥)</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>产品名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScheduleJobUtilities.cls
public class ScheduleJobUtilities {

  /*
     update customer monthly spending and total spending
   */
  public static void updateCustomerInfo(){
    // retrieve all customers
    List<Customer__c> customerList = [SELECT Id, Total_Spending_RMB__c, Monthly_Spending_RMB__c FROM Customer__c];

    // retrieve this month's all orders
    List<Order__c> orderList = [SELECT Customer__c,Total_Price_RMB__c FROM Order__c WHERE CreatedDate = THIS_MONTH];

    // create a spending map - key as customerId, value as this monthly total spending
    Map<Id, Decimal> spendingMap = new Map<Id, Decimal>();
    for(Order__c order : orderList) {
      if(spendingMap.get(order.Customer__c) == null) {
        spendingMap.put(order.Customer__c, order.Total_Price_RMB__c);
      }else{
        spendingMap.put(order.Customer__c, spendingMap.get(order.Customer__c) + order.Total_Price_RMB__c);
      }
    }

    // update customer info
    for(Customer__c customer : customerList) {
      customer.Monthly_Spending_RMB__c = spendingMap.keySet().contains(customer.Id) ? spendingMap.get(customer.Id) : 0;
      customer.Total_Spending_RMB__c = spendingMap.keySet().contains(customer.Id) ? customer.Total_Spending_RMB__c + spendingMap.get(customer.Id) : customer.Total_Spending_RMB__c + 0;
    }

    update customerList;
  }

  /*
     update FI STATS
   */
  public static void updateFISTATS(){
    // retrieve this month's total revenue and total cost
    AggregateResult[] arList = [SELECT SUM(Total_Cost_RMB__c) totalCost,SUM(Total_Price_RMB__c) totalRevenue FROM Order__c WHERE CreatedDate = THIS_MONTH];
    Decimal totalRevenue = Decimal.valueOf(String.valueOf(arList[0].get('totalRevenue')));
    Decimal totalCost = Decimal.valueOf(String.valueOf(arList[0].get('totalCost')));

    // retrieve this month's packet fees
    AggregateResult[] arList2 = [SELECT SUM(Cost_RMB__c) packetFeeTotal FROM Packet__c WHERE CREATEDDATE = THIS_MONTH];
    Decimal packetFeeTotal = Decimal.valueOf(String.valueOf(arList2[0].get('packetFeeTotal')));

    // insert a fiStats record
    FI_STATS__c fiStats = new FI_STATS__c();
    fiStats.Revenue_RMB__c = totalRevenue;
    fiStats.Profit_RMB__c = totalRevenue - totalCost - packetFeeTotal;
    insert fiStats;
  }

  /*
     update product info
   */
  public static void updateProductInfo(){
    // retrieve all products
    List<Product__c> productList = [SELECT Id, Current_Profit_RMB__c, Current_Revenue_RMB__c, Current_Quantity__c, Total_Profit_RMB__c, Total_Revenue_RMB__c, Total_Quantity__c FROM Product__c];

    // retrieve this month's sold products' total revenue and cost
    AggregateResult[] arList = [SELECT Product__c, SUM(Cost_RMB__c) totalCost, SUM(Price_RMB__c) totalRevenue, COUNT(Id) soldQuantities FROM OrderLineItem__c WHERE CREATEDDATE = THIS_MONTH GROUP BY Product__c];

    // create a productInfo map - key as productId, value as another map (key as 'totalCost', 'totalRevenue', 'soldQuantities', value as corresponding value)
    Map<Id, Map<String, String>> productInfoMap = new Map<Id, Map<String, String>>();
    for(AggregateResult ar : arList) {
      Map<String, String> productInfo = new Map<String, String>();
      productInfo.put('totalCost', String.valueOf(ar.get('totalCost')));
      productInfo.put('totalRevenue', String.valueOf(ar.get('totalRevenue')));
      productInfo.put('soldQuantities', String.valueOf(ar.get('soldQuantities')));
      productInfoMap.put(Id.valueOf(String.valueOf(ar.get('Product__c'))), productInfo);
    }

    // update product info
    for(Product__c product : productList) {
      product.Current_Quantity__c = productInfoMap.keySet().contains(product.Id) ? Integer.valueOf(productInfoMap.get(product.Id).get('soldQuantities')) : 0;
      product.Current_Revenue_RMB__c = productInfoMap.keySet().contains(product.Id) ? Decimal.valueOf(productInfoMap.get(product.Id).get('totalRevenue')) : 0;
      product.Current_Profit_RMB__c = productInfoMap.keySet().contains(product.Id) ? Decimal.valueOf(productInfoMap.get(product.Id).get('totalRevenue')) - Decimal.valueOf(productInfoMap.get(product.Id).get('totalCost')) : 0;

      product.Total_Quantity__c = productInfoMap.keySet().contains(product.Id) ? product.Total_Quantity__c + Integer.valueOf(productInfoMap.get(product.Id).get('soldQuantities')) : product.Total_Quantity__c + 0;
      product.Total_Revenue_RMB__c = productInfoMap.keySet().contains(product.Id) ? product.Total_Revenue_RMB__c + Decimal.valueOf(productInfoMap.get(product.Id).get('totalRevenue')) : product.Total_Revenue_RMB__c + 0;
      product.Total_Profit_RMB__c = productInfoMap.keySet().contains(product.Id) ? product.Total_Profit_RMB__c + Decimal.valueOf(productInfoMap.get(product.Id).get('totalRevenue')) - Decimal.valueOf(productInfoMap.get(product.Id).get('totalCost')) : product.Total_Profit_RMB__c + 0;
    }

    update productList;
  }

}