src/objects/Customer__c.object
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>微信昵称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <label>买家</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>订单</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状态</label>
        <picklist>
            <picklistValues>
                <fullName>Unfulfilled</fullName>
                <color>#FF6600</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled</fullName>
                <color>#3366FF</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>订单编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Cost_RMB__c</fullName>
        <label>成本(￥)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>订单</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>订单项</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Packet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>包裹</label>
        <referenceTo>Packet__c</referenceTo>
        <relationshipLabel>订单项</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_RMB__c</fullName>
        <label>价格(￥)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>产品</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderLineItems</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状态</label>
        <picklist>
            <picklistValues>
                <fullName>Undelivered</fullName>
                <color>#FF6666</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
                <color>#78C953</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>OrderLineItem</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>订单项编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Packet__c.object
<CustomObject>
    <fields>
        <fullName>Cost_RMB__c</fullName>
        <label>运费(￥)</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状态</label>
        <picklist>
            <picklistValues>
                <fullName>Undelivered</fullName>
                <color>#FF6666</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
                <color>#78C953</color>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Packet</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>包裹编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Price_RMB__c</fullName>
        <label>价格(￥)</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>产品名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PacketControllerExtension.cls
public with sharing class PacketControllerExtension {

  private final sObject packet;

  /* properties used for pagination */
  public Integer noOfRecords { get; set; }
  public Integer size { get; set; }

  /* parameters used for searching order line items (passed in by javascript function) */
  public String customerId { get; set; }
  public String productId { get; set; }

  /* comma delimited order line item ids for selected order line items (passed in by javascript function) */
  public String orderLineItemIds { get; set; }

  /* comma delimited order line item ids for order line items that need to be removed from current packet (passed in by javascript function) */
  public String removeOrderLineItemIds { get; set; }

  public PacketControllerExtension(ApexPages.StandardController stdController) {
    this.packet = (Packet__c)stdController.getRecord();
  }

  /* StandardSetController for pagination */
  public ApexPages.StandardSetController setCon {
    get {
      if(setCon == null) {
        size = 10;
        String queryString = this.constructQuery(productId,customerId);
        setCon = new ApexPages.StandardSetController(Database.getQueryLocator(queryString));
        setCon.setPageSize(size);
        noOfRecords = setCon.getResultSize();
      }

      return setCon;
    }
    set;
  }

  /*
     get SOQL query
   */
  private String constructQuery(String productId, String customerId){

    String query = 'SELECT Id, Name, Order__r.Customer__r.Name, Product__r.Name, Price_RMB__c, Cost_RMB__c FROM OrderLineItem__c WHERE Status__c = \'Undelivered\' AND Packet__c = NULL';

    if(customerId != null && customerId != 'novalue') {
      query += ' AND Order__r.Customer__c = \'' + customerId + '\'';
    }

    if(productId != null && productId != 'novalue') {
      query += ' AND Product__c = \'' + productId + '\'';
    }

    System.debug('***query '+query);
    return query;
  }

  /*
     get function for order line items
   */
  public List<OrderLineItem__c> getOrderLineItems(){
    List<OrderLineItem__c> orderLineItemList = new List<OrderLineItem__c>();
    if(setCon != null) {
      for(OrderLineItem__c orderLineItem : (List<OrderLineItem__c>)setCon.getRecords())
        orderLineItemList.add(orderLineItem);
    }

    return orderLineItemList;
  }

  /*
     get function for selected order line items
   */
  public List<OrderLineItem__c> getSelectedOrderLineItems(){
    List<OrderLineItem__c> orderLineItemList = [SELECT Id, Name, Order__r.Customer__r.Name, Product__r.Name, Price_RMB__c, Cost_RMB__c FROM OrderLineItem__c WHERE Packet__c = : this.packet.Id];
    return orderLineItemList;
  }

  /*
     search for order line items
   */
  public PageReference searchOrderLineItems(){
    setCon = null;
    getOrderLineItems();
    setCon.setPageNumber(1);
    return null;
  }

  /*
     select order line items
   */
  public PageReference selectOrderLineItems(){
    if(orderLineItemIds != null && orderLineItemIds.trim() != '') {
      List<String> orderLineItemIdList = orderLineItemIds.split(',');
      List<OrderLineItem__c> orderLineItemList = [SELECT Id, Packet__c FROM OrderLineItem__c WHERE Id IN : orderLineItemIdList];
      for (OrderLineItem__c orderLineItem : orderLineItemList) {
        orderLineItem.Packet__c = this.packet.Id;
      }
      update orderLineItemList;
    }

    PageReference pr = new PageReference('/'+this.packet.Id);
    pr.setRedirect(true);
    return pr;
  }

  /*
     remove order line items
   */
  public PageReference removeOrderLineItems(){
    if(removeOrderLineItemIds != null && removeOrderLineItemIds.trim() != '') {
      List<String> orderLineItemIdList = removeOrderLineItemIds.split(',');
      List<OrderLineItem__c> orderLineItemList = [SELECT Id, Packet__c FROM OrderLineItem__c WHERE Id IN : orderLineItemIdList];
      for (OrderLineItem__c orderLineItem : orderLineItemList) {
        orderLineItem.Packet__c = null;
      }
      update orderLineItemList;
    }

    PageReference pr = new PageReference('/'+this.packet.Id);
    pr.setRedirect(true);
    return pr;
  }

  /*
     get picklist values for customerName selector
   */
  @RemoteAction
  public static Map<String, String> getCustomerNames() {
    Map<String, String> optionsMap = new Map<String, String>();
    List<OrderLineItem__c> orderLineItemList = [SELECT Order__r.Customer__c, Order__r.Customer__r.Name FROM OrderLineItem__c WHERE Status__c = 'Undelivered' AND Packet__c = NULL];

    for (OrderLineItem__c orderLineItem : orderLineItemList) {
      optionsMap.put(orderLineItem.Order__r.Customer__r.Name, String.valueOf(orderLineItem.Order__r.Customer__c));
    }

    return optionsMap;
  }

  /*
     get picklist values for productName selector
   */
  @RemoteAction
  public static Map<String, String> getProductNames() {
    Map<String, String> optionsMap = new Map<String, String>();
    List<OrderLineItem__c> orderLineItemList = [SELECT Product__c, Product__r.Name FROM OrderLineItem__c WHERE Status__c = 'Undelivered' AND Packet__c = NULL];

    for (OrderLineItem__c orderLineItem : orderLineItemList) {
      optionsMap.put(orderLineItem.Product__r.Name, String.valueOf(orderLineItem.Product__c));
    }

    return optionsMap;
  }

}