src/objects/OrderLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Packet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>包裹</label>
        <referenceTo>Packet__c</referenceTo>
        <relationshipLabel>订单项</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状态</label>
        <picklist>
            <picklistValues>
                <fullName>Undelivered</fullName>
                <color>#FF6666</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
                <color>#78C953</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>OrderLineItem</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>订单项编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Packet__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>状态</label>
        <picklist>
            <picklistValues>
                <fullName>Undelivered</fullName>
                <color>#FF6666</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
                <color>#78C953</color>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Packet</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>包裹编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MoCWebservices.cls
global class MoCWebservices {

  webservice static void updatePacketStatus(Id packetId, String status){
    Packet__c packet = [SELECT Id, Status__c FROM Packet__c WHERE Id =: packetId];
    packet.Status__c = status;

    List<OrderLineItem__c> orderLineItemList = [SELECT Id, Status__c FROM OrderLineItem__c WHERE Packet__c =: packetId];
    for (OrderLineItem__c orderLineItem : orderLineItemList) {
      orderLineItem.Status__c = status;
    }

    update packet;
    update orderLineItemList;
  }

}