src/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>订单编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>品牌</label>
        <picklist>
            <controllingField>Minor_Category__c</controllingField>
            <picklistValues>
                <fullName>CaiZhuangPinPai2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CaiZhuangPinPai1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BaoJianPinPinPai2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BaoJianPinPinPai1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HuFuPinPai1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HuFuPinPai2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LingShiPinPai1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LingShiPinPai2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NeiYiPinPai1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NeiYiPinPai2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XiePinPai1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XiePinPai2</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Major_Category__c</fullName>
        <label>大类</label>
        <picklist>
            <picklistValues>
                <fullName>Apparel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Makeup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edible</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Minor_Category__c</fullName>
        <label>小类</label>
        <picklist>
            <controllingField>Major_Category__c</controllingField>
            <picklistValues>
                <fullName>CaiZhuang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BaoJianPin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HuFu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LingShi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NeiYi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Xie</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>产品名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderControllerExtension.cls
public class OrderControllerExtension {

  private final sObject order;

  public OrderControllerExtension(ApexPages.StandardController stdController) {
    this.order = (Order__c)stdController.getRecord();
  }

  @RemoteAction
  public static Map<String, String> getMajorCategories() {
    Map<String, String> optionsMap = new Map<String, String>();
    List<Schema.PicklistEntry> pleList = Product__c.Major_Category__c.getDescribe().getPicklistValues();

    for (Schema.PicklistEntry ple : pleList) {
      String label = ple.getLabel();
      String value = ple.getValue();
      optionsMap.put(label, value);
    }

    return optionsMap;
  }

  @RemoteAction
  public static Map<String, String> getMinorCategories(String majorCategory) {
    //***result {Apparel={内衣=NeiYi, 鞋=Xie}, Edible={保健品=BaoJianPin, 零食=LingShi}, Makeup={彩妆=CaiZhuang, 护肤=HuFu}}
    Map<String, Map<String,String>> result = HL_FieldDescribeUtil.getDependentOptionsImpl(Product__c.Minor_Category__c, Product__c.Major_Category__c);
    return result.get(majorCategory);
  }

  @RemoteAction
  public static Map<String, String> getBrands(String minorCategory) {
    //***result {BaoJianPin={保健品品牌一=BaoJianPinPinPai1, 保健品品牌二=BaoJianPinPinPai2}, CaiZhuang={彩妆品牌一=CaiZhuangPinPai1, 彩妆品牌二=CaiZhuangPinPai2}, HuFu={护肤品牌一=HuFuPinPai1, 护肤品牌二=HuFuPinPai2}, LingShi={零食品牌一=LingShiPinPai1, 零食品牌二=LingShiPinPai2}, NeiYi={内衣品牌一=NeiYiPinPai1, 内衣品牌二=NeiYiPinPai2}, Xie={鞋品牌一=XiePinPai1, 鞋品牌二=XiePinPai2}}
    Map<String, Map<String,String>> result = HL_FieldDescribeUtil.getDependentOptionsImpl(Product__c.Brand__c, Product__c.Minor_Category__c);
    return result.get(minorCategory);
  }

}